from __future__ import annotations

import json
import logging
import os
import threading
import time
from collections import OrderedDict

import yaml
from flask import Blueprint, jsonify, request, current_app
from pydantic import BaseModel
from sqlalchemy import select

from app.core.auth import require_permission
from app.db import get_session
from app.models.event import Event
from app.models.swarm import Swarm
from app.models.trigger import Trigger, KIND_HEARTBEAT, KIND_LISTENER, KIND_INVOCATION
from app.models.workspace import Workspace

bp = Blueprint("triggers", __name__, url_prefix="/api/v1")
logger = logging.getLogger(__name__)


# ── Listener deduplication ────────────────────────────────────────────────────

class _DedupeCache:
    """Thread-safe in-memory LRU dedup store with TTL.

    Keyed by an arbitrary string (typically payload.event_id).
    Returns True if the key was seen within the TTL window (duplicate).
    Evicts entries older than ttl_seconds on each write; also evicts the
    oldest entry when the cache is at capacity.
    """

    def __init__(self, ttl_seconds: int = 86400, max_size: int = 10_000) -> None:
        self._cache: OrderedDict[str, float] = OrderedDict()
        self._lock = threading.Lock()
        self._ttl = ttl_seconds
        self._max_size = max_size

    def is_duplicate(self, key: str) -> bool:
        """Return True if *key* is a recent duplicate; record it if not."""
        now = time.monotonic()
        with self._lock:
            if key in self._cache:
                return True
            # Evict expired entries (oldest first)
            cutoff = now - self._ttl
            while self._cache:
                oldest_key, oldest_ts = next(iter(self._cache.items()))
                if oldest_ts < cutoff:
                    self._cache.popitem(last=False)
                else:
                    break
            # Evict oldest entry if at capacity
            if len(self._cache) >= self._max_size:
                self._cache.popitem(last=False)
            self._cache[key] = now
            return False


_listener_dedup = _DedupeCache(ttl_seconds=86400, max_size=10_000)

_VALID_KINDS = {KIND_HEARTBEAT, KIND_LISTENER, KIND_INVOCATION}


# ── Heartbeat helpers ─────────────────────────────────────────────────────────

_DEFAULT_HEARTBEAT_SCRIPT = '''\
"""Default heartbeat script generated by the GUI.

Emits one ``heartbeat`` event per tick. The watermark advances to the
current UTC timestamp so the runtime can resume cleanly across restarts.
"""
import json
import sys
from datetime import datetime, timezone

now = datetime.now(timezone.utc).isoformat()
print(json.dumps({
    "watermark": now,
    "events": [
        {"type": "heartbeat", "payload": {"tick": now}}
    ],
}))
'''


def _ensure_heartbeat_script(swarm_id: str, name: str, config: dict, data_dir: str) -> dict:
    """If a heartbeat config is missing ``script``, generate a default one on disk
    and patch the config to point at it. Returns the (possibly mutated) config.
    """
    if config.get("script"):
        return config

    with get_session() as session:
        swarm = session.get(Swarm, swarm_id)
        if not swarm:
            return config
        workspace = session.get(Workspace, swarm.workspace_id)
        if not workspace:
            return config
        ws_name = workspace.name
        sw_name = swarm.name

    triggers_dir = os.path.join(data_dir, "workspaces", ws_name, "swarms", sw_name, "triggers")
    os.makedirs(triggers_dir, exist_ok=True)
    script_filename = f"{name}.py"
    script_path = os.path.join(triggers_dir, script_filename)
    if not os.path.isfile(script_path):
        with open(script_path, "w") as f:
            f.write(_DEFAULT_HEARTBEAT_SCRIPT)
        os.chmod(script_path, 0o755)
    config["script"] = script_filename
    return config


def _register_heartbeat_now(trigger_id: str) -> None:
    """Pick up a freshly-saved heartbeat trigger and register it with the
    running scheduler so it starts firing without a process restart.
    """
    from app.core.heartbeat import register_heartbeat_trigger

    data_dir = current_app.config["DATA_DIR"]
    with get_session() as session:
        trigger = session.get(Trigger, trigger_id)
        if not trigger:
            return
        # Detach a usable copy so we can drop the session before scheduling.
        session.expunge(trigger)
    try:
        register_heartbeat_trigger(current_app._get_current_object(), current_app.event_bus, data_dir, trigger)
    except Exception:
        logger.exception("Failed to register heartbeat %s", trigger_id)


def _deregister_heartbeat(trigger_id: str) -> None:
    try:
        from app.scheduler import remove_heartbeat
        remove_heartbeat(trigger_id)
    except Exception:
        logger.exception("Failed to remove heartbeat job %s", trigger_id)


# ── Trigger file helpers ──────────────────────────────────────────────────────

def _triggers_dir(swarm_id: str, data_dir: str) -> str | None:
    """Return the swarm's triggers/ directory path, creating it if needed."""
    with get_session() as session:
        swarm = session.get(Swarm, swarm_id)
        if not swarm:
            return None
        workspace = session.get(Workspace, swarm.workspace_id)
        if not workspace:
            return None
        path = os.path.join(
            data_dir, "workspaces", workspace.name, "swarms", swarm.name, "triggers"
        )
    os.makedirs(path, exist_ok=True)
    return path


def _write_trigger_yaml(triggers_dir: str, trigger: Trigger) -> None:
    config = json.loads(trigger.config_json or "{}")
    data = {"kind": trigger.kind, "enabled": trigger.enabled, "config": config}
    tmp = os.path.join(triggers_dir, f"{trigger.name}.yaml.tmp")
    dst = os.path.join(triggers_dir, f"{trigger.name}.yaml")
    with open(tmp, "w") as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    os.replace(tmp, dst)


def _delete_trigger_yaml(triggers_dir: str, name: str) -> None:
    path = os.path.join(triggers_dir, f"{name}.yaml")
    try:
        os.remove(path)
    except FileNotFoundError:
        pass


# ─────────────────────────────────────────────────────────────────────────────

class TriggerCreate(BaseModel):
    name: str
    kind: str
    config: dict = {}
    enabled: bool = True


class TriggerUpdate(BaseModel):
    name: str | None = None
    kind: str | None = None
    config: dict | None = None
    enabled: bool | None = None


@bp.get("/swarms/<swarm_id>/triggers")
def list_triggers(swarm_id: str):
    with get_session() as session:
        rows = session.execute(
            select(Trigger).where(Trigger.swarm_id == swarm_id).order_by(Trigger.name)
        ).scalars().all()
        return jsonify([t.to_dict() for t in rows])


@bp.post("/swarms/<swarm_id>/triggers")
@require_permission("can_manage_triggers")
def create_trigger(swarm_id: str):
    try:
        body = TriggerCreate.model_validate(request.get_json(force=True) or {})
    except Exception as exc:
        return jsonify({"error": {"code": "validation_error", "message": str(exc)}}), 400

    if body.kind not in _VALID_KINDS:
        return jsonify({
            "error": {
                "code": "invalid_kind",
                "message": f"kind must be one of: {', '.join(sorted(_VALID_KINDS))}",
            }
        }), 400

    with get_session() as session:
        if not session.get(Swarm, swarm_id):
            return jsonify({"error": {"code": "not_found", "message": "Swarm not found"}}), 404

    config = dict(body.config or {})

    # Friendly mapping for GUI: accept "cron" as an alias for "schedule".
    if body.kind == KIND_HEARTBEAT:
        if "cron" in config and "schedule" not in config:
            config["schedule"] = config.pop("cron")
        # Auto-generate a default tick script when none is supplied.
        config = _ensure_heartbeat_script(
            swarm_id, body.name, config, current_app.config["DATA_DIR"]
        )

    with get_session() as session:
        trigger = Trigger(
            swarm_id=swarm_id,
            name=body.name,
            kind=body.kind,
            config_json=json.dumps(config),
            enabled=body.enabled,
        )
        session.add(trigger)
        session.commit()
        session.refresh(trigger)
        result = trigger.to_dict()
        new_id = trigger.id

    tdir = _triggers_dir(swarm_id, current_app.config["DATA_DIR"])
    if tdir:
        with get_session() as session:
            t = session.get(Trigger, new_id)
            if t:
                _write_trigger_yaml(tdir, t)

    if body.kind == KIND_HEARTBEAT and body.enabled:
        _register_heartbeat_now(new_id)

    return jsonify(result), 201


@bp.put("/triggers/<trigger_id>")
@require_permission("can_manage_triggers")
def update_trigger(trigger_id: str):
    try:
        body = TriggerUpdate.model_validate(request.get_json(force=True) or {})
    except Exception as exc:
        return jsonify({"error": {"code": "validation_error", "message": str(exc)}}), 400

    with get_session() as session:
        trigger = session.get(Trigger, trigger_id)
        if not trigger:
            return jsonify({"error": {"code": "not_found", "message": "Trigger not found"}}), 404

        old_name   = trigger.name
        swarm_id   = trigger.swarm_id
        old_tdir   = _triggers_dir(swarm_id, current_app.config["DATA_DIR"])

        if body.name is not None:
            trigger.name = body.name
        if body.kind is not None:
            if body.kind not in _VALID_KINDS:
                return jsonify({
                    "error": {"code": "invalid_kind", "message": f"kind must be one of: {', '.join(sorted(_VALID_KINDS))}"}
                }), 400
            trigger.kind = body.kind
        if body.config is not None:
            trigger.config_json = json.dumps(body.config)
        if body.enabled is not None:
            trigger.enabled = body.enabled

        session.commit()
        session.refresh(trigger)
        result = trigger.to_dict()
        is_heartbeat = trigger.kind == KIND_HEARTBEAT
        is_enabled   = trigger.enabled

    if old_tdir:
        if body.name is not None and body.name != old_name:
            _delete_trigger_yaml(old_tdir, old_name)
        _write_trigger_yaml(old_tdir, trigger)

    # Reconcile the scheduler with the new state.
    if is_heartbeat:
        if is_enabled:
            _register_heartbeat_now(trigger_id)
        else:
            _deregister_heartbeat(trigger_id)

    return jsonify(result)


@bp.delete("/triggers/<trigger_id>")
@require_permission("can_manage_triggers")
def delete_trigger(trigger_id: str):
    with get_session() as session:
        trigger = session.get(Trigger, trigger_id)
        if not trigger:
            return jsonify({"error": {"code": "not_found", "message": "Trigger not found"}}), 404
        kind     = trigger.kind
        name     = trigger.name
        swarm_id = trigger.swarm_id
        tdir     = _triggers_dir(swarm_id, current_app.config["DATA_DIR"])
        session.delete(trigger)
        session.commit()

    if tdir:
        _delete_trigger_yaml(tdir, name)

    if kind == KIND_HEARTBEAT:
        _deregister_heartbeat(trigger_id)

    return "", 204


# ── Listener webhook ──────────────────────────────────────────────────────────

@bp.post("/triggers/listener/<path:suffix>")
@require_permission("can_start_run")
def listener_webhook(suffix: str):
    """Receive an inbound webhook for a listener trigger.

    The trigger is identified by the ``endpoint`` field in its config matching
    the URL suffix.  If the config declares a ``secret``, the request must
    carry ``Authorization: Bearer <secret>``.

    If the config includes a ``filter`` (a JSON-schema object), the request
    body is validated against it before the event is accepted.
    """
    # Find the matching listener trigger by endpoint suffix
    with get_session() as session:
        candidates = session.execute(
            select(Trigger).where(
                Trigger.kind == KIND_LISTENER,
                Trigger.enabled.is_(True),
            )
        ).scalars().all()

        trigger = None
        config: dict = {}
        for t in candidates:
            cfg = json.loads(t.config_json or "{}")
            if cfg.get("endpoint") == suffix:
                trigger = t
                config = cfg
                break

    if trigger is None:
        return jsonify({"error": {"code": "not_found", "message": "No listener trigger for this endpoint"}}), 404

    # Validate shared secret when configured
    expected_secret = config.get("secret")
    if expected_secret:
        auth = request.headers.get("Authorization", "")
        token = auth.removeprefix("Bearer ").strip()
        if token != expected_secret:
            return jsonify({"error": {"code": "unauthorized", "message": "Invalid or missing secret"}}), 401

    payload = request.get_json(force=True, silent=True) or {}

    # Deduplication: if payload carries an event_id we've seen in the last 24h, drop it
    event_id_key = payload.get("event_id")
    if event_id_key is not None:
        dedup_key = f"{trigger.id}:{event_id_key}"
        if _listener_dedup.is_duplicate(dedup_key):
            logger.debug("Listener %s: duplicate event_id %r — dropped", trigger.id, event_id_key)
            return jsonify({"deduplicated": True, "event_id": str(event_id_key)}), 202

    # Optional JSON-schema filter
    schema_filter = config.get("filter")
    if schema_filter:
        try:
            import jsonschema  # noqa: PLC0415
            jsonschema.validate(instance=payload, schema=schema_filter)
        except jsonschema.ValidationError as exc:
            return jsonify({"error": {"code": "filter_mismatch", "message": str(exc.message)}}), 422
        except Exception as exc:
            logger.warning("Listener filter error for trigger %s: %s", trigger.id, exc)

    # Persist and publish
    payload.setdefault("type", "listener")
    # Per-trigger target_agent overrides the swarm's entry_point (Phase 6.1).
    if config.get("target_agent"):
        payload["_target_agent"] = config["target_agent"]

    with get_session() as session:
        event = Event(
            swarm_id=trigger.swarm_id,
            trigger_id=trigger.id,
            source="listener",
            payload_json=json.dumps(payload),
        )
        session.add(event)
        session.commit()
        session.refresh(event)

    current_app.event_bus.publish(event)
    return jsonify({"event_id": event.id}), 202


# ── Invocation endpoint ───────────────────────────────────────────────────────

@bp.post("/triggers/invocations/<trigger_id>")
@require_permission("can_start_run")
def invoke_trigger(trigger_id: str):
    """Manually invoke a swarm via an invocation trigger.

    The request body is the event payload.  An ``invoked_by`` field may be
    included to identify the caller; it defaults to ``"anonymous"``.

    The invocation config may include a ``schema`` field (JSON Schema) to
    validate the submitted payload before the event is created.
    """
    with get_session() as session:
        trigger = session.get(Trigger, trigger_id)
        if not trigger:
            return jsonify({"error": {"code": "not_found", "message": "Trigger not found"}}), 404
        if trigger.kind != KIND_INVOCATION:
            return jsonify({"error": {"code": "wrong_kind", "message": "Trigger is not an invocation"}}), 400
        if not trigger.enabled:
            return jsonify({"error": {"code": "disabled", "message": "Trigger is disabled"}}), 409

        config = json.loads(trigger.config_json or "{}")
        swarm_id = trigger.swarm_id
        t_id = trigger.id

    body_payload = request.get_json(force=True, silent=True) or {}
    invoked_by = body_payload.pop("invoked_by", "anonymous")

    payload_schema = config.get("payload_schema")
    if payload_schema:
        # New schema-based payload assembly:
        # 1. Start with any extra free-form fields from the caller.
        payload = dict(body_payload)
        # 2. Merge fixed fields (always override caller input).
        for field in payload_schema:
            key  = field.get("key")
            mode = field.get("mode", "input")
            if not key:
                continue
            if mode == "fixed":
                payload[key] = field.get("value")
            elif key not in payload:
                if field.get("required"):
                    return jsonify({"error": {
                        "code": "missing_field",
                        "message": f"Required field '{key}' not provided",
                    }}), 422
                if "default" in field:
                    payload[key] = field["default"]
        # 3. Auto-parse text fields that contain valid JSON — the GUI
        #    collects structured data as raw JSON text in textareas.
        for key, val in list(payload.items()):
            if isinstance(val, str):
                stripped = val.strip()
                if stripped and stripped[0] in ("{", "["):
                    try:
                        payload[key] = json.loads(stripped)
                    except (json.JSONDecodeError, ValueError):
                        pass
    elif not body_payload and config.get("default_payload"):
        # Legacy: fall back to stored default_payload when body is empty.
        payload = dict(config["default_payload"])
    else:
        payload = body_payload

    # Optional JSON-Schema validation (legacy config.schema field)
    schema = config.get("schema")
    if schema:
        try:
            import jsonschema  # noqa: PLC0415
            jsonschema.validate(instance=payload, schema=schema)
        except jsonschema.ValidationError as exc:
            return jsonify({"error": {"code": "validation_error", "message": exc.message}}), 422

    payload.setdefault("type", "invocation")
    payload["invoked_by"] = invoked_by
    if config.get("target_agent"):
        payload["_target_agent"] = config["target_agent"]

    with get_session() as session:
        event = Event(
            swarm_id=swarm_id,
            trigger_id=t_id,
            source="invocation",
            payload_json=json.dumps(payload),
        )
        session.add(event)
        session.commit()
        session.refresh(event)

    current_app.event_bus.publish(event)
    return jsonify({"event_id": event.id}), 202
