services:
  swarm:
    image: ralphbarendse/swarmwright:latest
    network_mode: host
    volumes:
      - ../data:/data
    env_file:
      - path: ../.env
        required: false
    restart: unless-stopped
