services:
  swarm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    volumes:
      - ../data:/data
    env_file:
      - ../.env
    restart: unless-stopped
